---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    
  mongodb:
    restart: always
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    logging:
      options: 
        max-size: 1g
    environment:
      - MONGO_INITDB_DATABASE=NASA_data
    volumes:
      - ./data:/data/db

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: consumer
    depends_on:
      - broker
    volumes:
      - ./consumer.py:/app/consumer.py
      - ./getting_started.ini:/app/getting_started.ini
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'localhost:9092'
    command: python /app/consumer.py /app/getting_started.ini

  consumer2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: consumer2
    depends_on:
      - broker
    volumes:
      - ./consumer2.py:/app/consumer2.py
      - ./getting_started.ini:/app/getting_started.ini
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'localhost:9092'
    command: python consumer2.py getting_started.ini
  
  consumer3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: consumer3
    depends_on:
      - broker
    volumes:
      - ./consumer3.py:/app/consumer3.py
      - ./getting_started.ini:/app/getting_started.ini
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'localhost:9092'
    command: python consumer3.py getting_started.ini

  consumer4:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: consumer4
    depends_on:
      - broker
    volumes:
      - ./consumer4.py:/app/consumer4.py
      - ./getting_started.ini:/app/getting_started.ini
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'localhost:9092'
    command: python consumer4.py getting_started.ini

  producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: producer
    depends_on:
      - broker
    volumes:
      - ./producer.py:/app/producer.py
      - ./getting_started.ini:/app/getting_started.ini
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'localhost:9092'
    command: python producer.py getting_started.ini

  producer2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: producer2
    depends_on:
      - broker
    volumes:
      - ./producer2.py:/app/producer2.py
      - ./getting_started.ini:/app/getting_started.ini
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'localhost:9092'
    command: python producer2.py getting_started.ini

  producer3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: producer3
    depends_on:
      - broker
    volumes:
      - ./producer3.py:/app/producer3.py
      - ./getting_started.ini:/app/getting_started.ini  
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'localhost:9092'
    command: python producer3.py getting_started.ini

  producer4:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: producer4
    depends_on:
      - broker
    volumes:
      - ./producer4.py:/app/producer4.py
      - ./getting_started.ini:/app/getting_started.ini
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'localhost:9092'
    command: python producer4.py getting_started.ini